version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  generate-password:
    lang: node24
    handler: ./generate-password
    image: ghcr.io/mspr2-2026/generate-password:latest
    environment:
      COUCHDB_URL: "http://couchdb-couchdb.default:5984"
    secrets:
      - couchdb-user
      - couchdb-password
  generate-2fa:
    lang: node24
    handler: ./generate-2fa
    image: ghcr.io/mspr2-2026/generate-2fa:latest
    environment:
      COUCHDB_URL: "http://couchdb-couchdb.default:5984"
    secrets:
      - couchdb-user
      - couchdb-password
